replicaCount: 2

awsRegion: "ap-south-1"

image:
  repository: "ghcr.io/h1zardian/devsecops-pipeline-project"
  pullPolicy: IfNotPresent
  tag: "sha-c9487d9"

sqlHost: "devsecops-postgres-dev.cmksk3juhzgm.ap-south-1.rds.amazonaws.com"
allowedHosts: "app.example.com"

externalSecrets:
  enabled: true
  environment: "dev"
  secretKey: "django-insecure-dev-key-change-in-prod"
  postgresPassword: "postgrespassword"

serviceAccount:
  create: true
  name: django-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::072329308666:role/devsecops-eso-irsa-role-dev"

ingress:
  enabled: true
  className: nginx
  host: app.example.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
