apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: django-app
  {{- if .Values.gitOps.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  {{- end }}
data:
  ALLOWED_HOSTS: {{ .Values.allowedHosts | default .Values.ingress.host | quote }}
  PYTHONDONTWRITEBYTECODE: "1"
  DATABASE: "postgres"
  SQL_ENGINE: "django.db.backends.postgresql"
  POSTGRES_DB: "hospital_db"
  POSTGRES_USER: "postgres"
  SQL_PORT: "5432"
  SQL_HOST: {{ .Values.sqlHost | quote }}
