apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "django-app.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: django-app
  {{- if or .Values.gitOps.enabled .Values.serviceAccount.annotations }}
  annotations:
    {{- if .Values.gitOps.enabled }}
    argocd.argoproj.io/sync-wave: "-2"
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
