apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-resource-limits
  annotations:
    policies.kyverno.io/title: Require Resource Limits
    policies.kyverno.io/category: Best Practices
spec:
  admission: true
  validationFailureAction: Enforce
  background: true
  emitWarning: false
  rules:
    - name: validate-resources
      skipBackgroundRequests: true
      match:
        any:
          - resources:
              kinds: [Pod]
              namespaces: [django]
      validate:
        allowExistingViolations: true
        message: "CPU and Memory resource requests/limits must be specified for all containers."
        pattern:
          spec:
            containers:
              - resources:
                  requests:
                    cpu: "?*"
                    memory: "?*"
                  limits:
                    cpu: "?*"
                    memory: "?*"
